# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ironfan"
  s.version = "3.1.4.serengeti.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Infochimps"]
  s.date = "2012-05-30"
  s.description = "Ironfan allows you to orchestrate not just systems but clusters of machines. It includes a powerful layer on top of knife and a collection of cloud cookbooks."
  s.email = "coders@infochimps.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md",
    "README.textile"
  ]

  s.homepage = "http://infochimps.com/labs"
  s.licenses = ["apachev2"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Ironfan allows you to orchestrate not just systems but clusters of machines. It includes a powerful layer on top of knife and a collection of cloud cookbooks."

  s.files = `git ls-files`.split("\n")
  s.test_files = `git ls-files -- {spec,tests}/*`.split("\n")

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chef>, ["~> 0.10.4"])
      s.add_dependency(%q<fog>, ["~> 1.3.1.serengeti.1"])
      s.add_runtime_dependency(%q<formatador>, ["~> 0.2.1"])
      s.add_runtime_dependency(%q<gorillib>, ["~> 0.1.7"])
      s.add_dependency(%q<cloud-manager>, ["~> 0.5.0"])
#      s.add_development_dependency(%q<bundler>, ["~> 1"])
#      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
#      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
#      s.add_development_dependency(%q<yard>, ["~> 0.6"])
#      s.add_development_dependency(%q<redcarpet>, ["~> 2"])
    else
      s.add_dependency(%q<chef>, ["~> 0.10.4"])
      s.add_dependency(%q<fog>, ["~> 1.3.1.serengeti.1"])
      s.add_dependency(%q<formatador>, ["~> 0.2.1"])
      s.add_dependency(%q<gorillib>, ["~> 0.1.7"])
      s.add_dependency(%q<cloud-manager>, ["~> 0.5.0"])
#      s.add_dependency(%q<bundler>, ["~> 1"])
#      s.add_dependency(%q<jeweler>, ["~> 1.6"])
#      s.add_dependency(%q<rspec>, ["~> 2.5"])
#      s.add_dependency(%q<yard>, ["~> 0.6"])
#      s.add_dependency(%q<redcarpet>, ["~> 2"])
    end
  else
    s.add_dependency(%q<chef>, ["~> 0.10.4"])
    s.add_dependency(%q<fog>, ["~> 1.3.1.serengeti.1"])
    s.add_dependency(%q<formatador>, ["~> 0.2.1"])
    s.add_dependency(%q<gorillib>, ["~> 0.1.7"])
    s.add_dependency(%q<cloud-manager>, ["~> 0.5.0"])
#    s.add_dependency(%q<bundler>, ["~> 1"])
#    s.add_dependency(%q<jeweler>, ["~> 1.6"])
#    s.add_dependency(%q<rspec>, ["~> 2.5"])
#    s.add_dependency(%q<yard>, ["~> 0.6"])
#    s.add_dependency(%q<redcarpet>, ["~> 2"])
  end
end

